CONTIKI_PROJECT = sensor-mote root-mote computation-mote
PROJECT_SOURCEFILES = computation.c routing.c hashmap.c trickle-timer.c 

all: $(CONTIKI_PROJECT)

CONTIKI_WITH_RIME = 1
CONTIKI = ../../contiki
include $(CONTIKI)/Makefile.include